import {
  Activity,
  Armchair,
  Atom,
  Baby,
  Biohazard,
  Bone,
  BookOpen,
  Brain,
  BrainCog,
  Bug,
  Dna,
  Droplet,
  Droplets,
  Ear,
  Eye,
  FlaskConical,
  Hand,
  HeartPulse,
  House,
  Layers,
  MessageCircleHeart,
  Microscope,
  Moon,
  Pill,
  Ribbon,
  Scale,
  ScanLine,
  Scissors,
  ShieldPlus,
  Siren,
  Stethoscope,
  Sun,
  Syringe,
  Thermometer,
  UsersRound,
  Utensils,
  Venus,
  Waves,
  Wind,
  type LucideIcon,
} from 'lucide-react'

// Nome usado no campo "icone" do JSON da matéria -> ícone desenhado
const icones: Record<string, LucideIcon> = {
  osso: Bone,
  coracao: HeartPulse,
  frasco: FlaskConical,
  pilula: Pill,
  microscopio: Microscope,
  estetoscopio: Stethoscope,
  bisturi: Scissors,
  bebe: Baby,
  gestante: Venus,
  comunidade: UsersRound,
  camadas: Layers,
  atomo: Atom,
  dna: Dna,
  pulso: Activity,
  escudo: ShieldPlus,
  microbio: Biohazard,
  inseto: Bug,
  conversa: MessageCircleHeart,
  balanca: Scale,
  pulmao: Wind,
  digestivo: Utensils,
  rim: Droplets,
  seringa: Syringe,
  sangue: Droplet,
  mao: Hand,
  termometro: Thermometer,
  cerebro: Brain,
  mente: BrainCog,
  pele: Sun,
  laco: Ribbon,
  poltrona: Armchair,
  ondas: Waves,
  ouvido: Ear,
  olho: Eye,
  sono: Moon,
  imagem: ScanLine,
  sirene: Siren,
  casa: House,
}

export function IconeMateria({ nome, className = '' }: { nome: string; className?: string }) {
  const Icone = icones[nome] ?? BookOpen
  return <Icone className={className} strokeWidth={2.4} aria-hidden />
}
